[project]
name = "ai-resume-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "easyocr>=1.7.2",
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "httpx>=0.28.1",
    "pyjwt>=2.13.0",
    "pillow>=12.3.0",
    "pyjwt>=2.13.0",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.52.3",
    "rapidfuzz>=3.14.5",
    "openai>=3.3.1",
    "slowapi>=0.1.10",
]
